// svelte/src/routes/home.20250619/components/feed-cards/MyPreferencesChart.svelte
<script lang="ts">
	import { BarChart, Calendar, Heart, Bookmark, MapPin } from 'lucide-svelte';

	interface PreferenceItem {
		name: string;
		likes: number;
		saves: number;
		visits: number;
		total: number;
	}

	interface MyPreferencesData {
		id: string;
		title: string;
		period: string;
		regionPreferences: PreferenceItem[];
		categoryPreferences: PreferenceItem[];
		summary: {
			totalActivities: number;
			topRegion: string;
			topCategory: string;
			mostLikedRegion: string;
			mostVisitedCategory: string;
		};
		timestamp: string;
	}

	const { card } = $props<{ card: MyPreferencesData }>();

	let showAllRegions = $state(false);
	let showAllCategories = $state(false);
	let currentView = $state(0); // 0: 합계, 1: 좋아요, 2: 저장, 3: 방문

	const viewLabels = ['전체', '좋아요', '저장', '방문'];
	const viewIcons = [BarChart, Heart, Bookmark, MapPin];

	function getTopItems(items: PreferenceItem[], showAll: boolean): PreferenceItem[] {
		return showAll ? items : items.slice(0, 4);
	}

	function getValueByView(item: PreferenceItem, view: number): number {
		switch (view) {
			case 0: return item.total;
			case 1: return item.likes;
			case 2: return item.saves;
			case 3: return item.visits;
			default: return item.total;
		}
	}

	function getMaxValue(items: PreferenceItem[], view: number): number {
		return Math.max(...items.map(item => getValueByView(item, view)));
	}

	function toggleRegions() {
		showAllRegions = !showAllRegions;
	}

	function toggleCategories() {
		showAllCategories = !showAllCategories;
	}

	function changeView(index: number) {
		currentView = index;
	}
</script>

<article class="bg-white rounded-lg shadow-sm mb-3 overflow-hidden border border-gray-100">
	<!-- 헤더 -->
	<header class="p-4 pb-3">
		<div class="flex items-center justify-between">
			<div class="flex items-center gap-2">
				<div class="flex items-center gap-1 px-2 py-1 bg-gray-100 rounded-full">
					<BarChart class="w-3 h-3 text-gray-600" />
					<span class="text-xs font-medium text-gray-700">내 취향 분석</span>
				</div>
				<div class="px-2 py-1 bg-gray-50 rounded-full">
					<span class="text-xs font-medium text-gray-600">{card.period}</span>
				</div>
			</div>
			<Calendar class="w-4 h-4 text-gray-400" />
		</div>
	</header>

	<div class="p-4 pt-0">
		<!-- 타이틀 -->
		<h3 class="font-semibold text-gray-900 text-lg mb-4">{card.title}</h3>

		<!-- 활동 요약 -->
		<div class="bg-gray-50 rounded-lg p-4 mb-4">
			<h4 class="text-sm font-medium text-gray-700 mb-3">활동 요약</h4>
			<div class="grid grid-cols-2 gap-4 text-center">
				<div>
					<p class="text-2xl font-bold text-gray-900">{card.summary.totalActivities}</p>
					<p class="text-xs text-gray-500">총 활동</p>
				</div>
				<div>
					<p class="text-lg font-medium text-gray-900">{card.regionPreferences.length}</p>
					<p class="text-xs text-gray-500">지역 탐방</p>
				</div>
			</div>
			<div class="mt-3 pt-3 border-t border-gray-200 space-y-1">
				<p class="text-sm text-gray-600">가장 많이 간 지역: <span class="font-medium text-gray-900">{card.summary.topRegion}</span></p>
				<p class="text-sm text-gray-600">선호 음식 종류: <span class="font-medium text-gray-900">{card.summary.topCategory}</span></p>
			</div>
		</div>

		<!-- 활동별 보기 탭 -->
		<div class="flex items-center gap-1 mb-4 p-1 bg-gray-100 rounded-lg">
			{#each viewLabels as label, index}
				{@const SvelteComponent = viewIcons[index]}
				<button
					class="flex-1 flex items-center justify-center gap-1 px-3 py-2 text-xs font-medium rounded-md transition-colors {currentView === index ? 'bg-white text-gray-900 shadow-sm' : 'text-gray-600 hover:text-gray-900'}"
					onclick={() => changeView(index)}
				>
					<SvelteComponent class="w-3 h-3" />
					{label}
				</button>
			{/each}
		</div>

		<!-- 지역별 선호도 -->
		<div class="mb-6">
			<div class="flex items-center justify-between mb-3">
				<h4 class="font-medium text-gray-900">지역별 선호도</h4>
				{#if card.regionPreferences.length > 4}
					<button
						class="text-xs text-gray-500 hover:text-gray-700 transition-colors"
						onclick={toggleRegions}
					>
						{showAllRegions ? '접기' : `+${card.regionPreferences.length - 4}개 더보기`}
					</button>
				{/if}
			</div>
			
			<div class="space-y-2">
				{#each getTopItems(card.regionPreferences, showAllRegions) as region}
					{@const value = getValueByView(region, currentView)}
					{@const maxValue = getMaxValue(card.regionPreferences, currentView)}
					<div class="flex items-center gap-3">
						<div class="w-12 text-sm text-gray-600 text-right">{region.name}</div>
						<div class="flex-1 relative">
							<div class="w-full h-6 bg-gray-100 rounded-full overflow-hidden">
								<div 
									class="h-full bg-gray-800 rounded-full transition-all duration-500 flex items-center justify-end pr-2"
									style="width: {maxValue > 0 ? (value / maxValue) * 100 : 0}%"
								>
									{#if value > 0}
										<span class="text-xs text-white font-medium">{value}</span>
									{/if}
								</div>
							</div>
						</div>
						<div class="w-8 text-xs text-gray-500 text-right">
							{maxValue > 0 ? Math.round((value / maxValue) * 100) : 0}%
						</div>
					</div>
				{/each}
			</div>
		</div>

		<!-- 카테고리별 선호도 -->
		<div class="mb-4">
			<div class="flex items-center justify-between mb-3">
				<h4 class="font-medium text-gray-900">음식 카테고리별 선호도</h4>
				{#if card.categoryPreferences.length > 4}
					<button
						class="text-xs text-gray-500 hover:text-gray-700 transition-colors"
						onclick={toggleCategories}
					>
						{showAllCategories ? '접기' : `+${card.categoryPreferences.length - 4}개 더보기`}
					</button>
				{/if}
			</div>
			
			<div class="space-y-2">
				{#each getTopItems(card.categoryPreferences, showAllCategories) as category}
					{@const value = getValueByView(category, currentView)}
					{@const maxValue = getMaxValue(card.categoryPreferences, currentView)}
					<div class="flex items-center gap-3">
						<div class="w-12 text-sm text-gray-600 text-right">{category.name}</div>
						<div class="flex-1 relative">
							<div class="w-full h-6 bg-gray-100 rounded-full overflow-hidden">
								<div 
									class="h-full bg-gray-800 rounded-full transition-all duration-500 flex items-center justify-end pr-2"
									style="width: {maxValue > 0 ? (value / maxValue) * 100 : 0}%"
								>
									{#if value > 0}
										<span class="text-xs text-white font-medium">{value}</span>
									{/if}
								</div>
							</div>
						</div>
						<div class="w-8 text-xs text-gray-500 text-right">
							{maxValue > 0 ? Math.round((value / maxValue) * 100) : 0}%
						</div>
					</div>
				{/each}
			</div>
		</div>

		<!-- 취향 인사이트 -->
		<div class="bg-gray-50 rounded-lg p-4">
			<h4 class="text-sm font-medium text-gray-700 mb-3">취향 인사이트</h4>
			<div class="space-y-2">
				<div class="flex items-center gap-2 text-xs">
					<div class="w-2 h-2 bg-gray-800 rounded-full"></div>
					<span class="text-gray-600">{card.summary.topRegion}에서 가장 활발하게 활동</span>
				</div>
				<div class="flex items-center gap-2 text-xs">
					<div class="w-2 h-2 bg-gray-800 rounded-full"></div>
					<span class="text-gray-600">{card.summary.topCategory} 음식을 가장 선호</span>
				</div>
				<div class="flex items-center gap-2 text-xs">
					<div class="w-2 h-2 bg-gray-800 rounded-full"></div>
					<span class="text-gray-600">{card.regionPreferences.length}개 지역, {card.categoryPreferences.length}개 카테고리 경험</span>
				</div>
			</div>
		</div>
	</div>
</article>

// src/features/profile/ui/MyPreferencesChart.tsx
import { useState, useMemo } from "react";
import { BarChart, Heart, Bookmark, MapPin } from "lucide-react";
import { cn } from "@/shared/lib/utils";
import type { 
  UserPlacesStatsBucket, 
  UserPlaceRegionStats, 
  UserPlaceCategorizedStats 
} from "@/entities/user/types";

// ----------------------- 타입 정의 -----------------------
interface PreferenceItem {
  name: string;
  total: number;
  likes: number;
  saves: number;
  visits: number;
}

interface PreferenceCardData {
  title: string;
  period: string;
  summary: {
    totalActivities: number; // 총 활동(좋아요+저장+방문 합계)
    topRegion: string; // 최다 활동 지역명
    topCategory: string; // 최다 활동 카테고리명
  };
  regionPreferences: PreferenceItem[]; // 지역별 선호도
  categoryPreferences: PreferenceItem[]; // 카테고리별 선호도(Top10 + 기타)
}

interface MyPreferencesChartProps {
  bucket?: UserPlacesStatsBucket | null;
}

// ----------------------- 데이터 가공 로직 ------------------------------
function mapRegionStats(stats: UserPlaceRegionStats[]): PreferenceItem[] {
  return stats
    .map((s) => ({
      name: s.agg_group,
      total: s.all,
      likes: s.liked,
      saves: s.saved,
      visits: s.visited,
    }))
    .sort((a, b) => b.total - a.total);
}

function mapCategoryStats(stats: UserPlaceCategorizedStats[]): PreferenceItem[] {
  const items: PreferenceItem[] = stats
    .map((s) => ({
      name: s.agg_group,
      total: s.all,
      likes: s.liked,
      saves: s.saved,
      visits: s.visited,
    }))
    .sort((a, b) => b.total - a.total);

  if (items.length <= 10) return items;

  const top10 = items.slice(0, 10);
  const others = items.slice(10);

  const aggregate = {
    name: '기타',
    total: others.reduce((sum, i) => sum + i.total, 0),
    likes: others.reduce((sum, i) => sum + i.likes, 0),
    saves: others.reduce((sum, i) => sum + i.saves, 0),
    visits: others.reduce((sum, i) => sum + i.visits, 0),
  };

  return [...top10, aggregate];
}

function formatDate(dateStr: string): string {
  const d = new Date(dateStr);
  return `${d.getFullYear()}.${(d.getMonth() + 1).toString().padStart(2, '0')}.${d
    .getDate()
    .toString()
    .padStart(2, '0')}`;
}

function parseBucket(b: UserPlacesStatsBucket | undefined): PreferenceCardData {
  if (!b) {
    return {
      title: '내 취향 분석',
      period: '-',
      summary: { totalActivities: 0, topRegion: '-', topCategory: '-' },
      regionPreferences: [],
      categoryPreferences: [],
    };
  }
  const regionStats = b.bucket_data_jsonb.v1_aggr_user_places_region_stats || [];
  const categoryStats = b.bucket_data_jsonb.v1_aggr_user_places_categorized_stats || [];

  const regionPreferences = mapRegionStats(regionStats);
  const categoryPreferences = mapCategoryStats(categoryStats);

  const totalActivities = regionStats.reduce((sum, r) => sum + r.all, 0);

  return {
    title: '내 활동과 취향 분석',
    period: formatDate(b.bucket_created_at),
    summary: {
      totalActivities,
      topRegion: regionPreferences[0]?.name || '-',
      topCategory: categoryPreferences[0]?.name || '-',
    },
    regionPreferences,
    categoryPreferences,
  };
}

export function MyPreferencesChart({ bucket }: MyPreferencesChartProps) {
  const [showAllRegions, setShowAllRegions] = useState(false);
  const [showAllCategories, setShowAllCategories] = useState(false);
  const [currentView, setCurrentView] = useState(0); // 0: 합계, 1: 좋아요, 2: 저장, 3: 방문

  const card = useMemo(() => parseBucket(bucket || undefined), [bucket]);

  const viewLabels = ['전체', '좋아요', '저장', '방문'];
  const ViewIcons = [BarChart, Heart, Bookmark, MapPin];

  function getTopItems(items: PreferenceItem[], showAll: boolean): PreferenceItem[] {
    return showAll ? items : items.slice(0, 4);
  }

  function getValueByView(item: PreferenceItem, view: number): number {
    switch (view) {
      case 0: return item.total;
      case 1: return item.likes;
      case 2: return item.saves;
      case 3: return item.visits;
      default: return item.total;
    }
  }

  return (
    <article className="mb-3 overflow-hidden rounded-lg border border-gray-100 bg-white shadow-sm">
      {/* 헤더 */}
      <header className="p-4 pb-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="flex items-center gap-1 rounded bg-gray-100 px-2 py-1">
              <BarChart className="h-3 w-3 text-gray-600" />
              <span className="text-xs font-medium text-gray-700">내 취향 분석</span>
            </div>
            <div className="flex items-center gap-1 rounded bg-gray-100 px-2 py-1">
              <span className="text-xs font-medium text-gray-600">{card.period} 기준</span>
            </div>
          </div>
        </div>
      </header>

      <div className="p-4 pt-0">
        {/* 타이틀 */}
        <h3 className="mb-4 text-lg font-semibold text-gray-900">{card.title}</h3>

        {/* 활동 요약 */}
        <div className="mb-4 rounded-lg bg-gray-50 p-4">
          <h4 className="mb-3 text-sm font-medium text-gray-700">활동 요약</h4>
          <div className="grid grid-cols-2 gap-4 text-center">
            <div>
              <p className="text-2xl font-medium text-gray-900">{card.summary.totalActivities}</p>
              <p className="text-xs text-gray-500">총 활동</p>
            </div>
            <div>
              <p className="text-2xl font-medium text-gray-900">
                {card.regionPreferences.filter((r) => r.visits > 0).length}
                <span className="text-sm">/ 14</span>
              </p>
              <p className="text-xs text-gray-500">지역 방문</p>
            </div>
          </div>
          <div className="mt-3 space-y-1 border-t border-gray-200 pt-3">
            <p className="text-sm text-gray-600">
              가장 많이 방문한 지역: <span className="font-medium text-gray-900">
                {card.summary.topRegion}
              </span>
            </p>
            <p className="text-sm text-gray-600">
              선호 음식 종류: <span className="font-medium text-gray-900">{card.summary.topCategory}</span>
            </p>
          </div>
        </div>

        {/* 활동별 보기 탭 */}
        <div className="mb-4 flex items-center gap-1 rounded-lg bg-gray-100 p-1">
          {viewLabels.map((label, index) => {
            const Icon = ViewIcons[index];
            return (
              <button
                key={label}
                className={cn(
                  "flex flex-1 items-center justify-center gap-1 rounded-md px-3 py-2 text-xs font-medium transition-colors",
                  currentView === index
                    ? "bg-white text-gray-900 shadow-sm"
                    : "text-gray-600 hover:text-gray-900"
                )}
                onClick={() => setCurrentView(index)}
              >
                <Icon className="h-3 w-3" />
                {label}
              </button>
            );
          })}
        </div>

        {/* 지역별 선호도 */}
        <div className="mb-6">
          <div className="mb-3 flex items-center justify-between">
            <h4 className="font-medium text-gray-900">지역별 선호도</h4>
            {card.regionPreferences.length > 4 && (
              <button
                className="text-xs text-gray-500 transition-colors hover:text-gray-700"
                onClick={() => setShowAllRegions(!showAllRegions)}
              >
                {showAllRegions ? '접기' : `+${card.regionPreferences.length - 4}개 더보기`}
              </button>
            )}
          </div>

          <div className="space-y-2">
            {card.regionPreferences.length === 0 ? (
              <p className="py-4 text-center text-sm text-gray-500">데이터가 없습니다.</p>
            ) : (
              getTopItems(card.regionPreferences, showAllRegions).map((region) => {
                const value = getValueByView(region, currentView);
                const totalValue = card.regionPreferences.reduce(
                  (sum, item) => sum + getValueByView(item, currentView),
                  0
                );
                const percentage = totalValue > 0 ? Math.round((value / totalValue) * 100) : 0;
                
                return (
                  <div key={region.name} className="flex items-center gap-3">
                    <div className="w-12 text-right text-sm text-gray-600">{region.name}</div>
                    <div className="relative flex-1">
                      <div className="h-6 w-full overflow-hidden rounded-full bg-gray-100">
                        {value > 0 && (
                          <div
                            className="flex h-full items-center justify-end rounded-full bg-gray-800 pr-2 transition-all duration-500"
                            style={{ width: `${percentage}%` }}
                          >
                            {percentage >= 10 && (
                              <span className="text-xs font-medium text-white">{percentage}%</span>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                    <div className="w-10 text-right text-xs text-gray-500">
                      {value}
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>

        {/* 카테고리별 선호도 */}
        <div className="mb-4">
          <div className="mb-3 flex items-center justify-between">
            <h4 className="font-medium text-gray-900">음식 카테고리별 선호도</h4>
            {card.categoryPreferences.length > 4 && (
              <button
                className="text-xs text-gray-500 transition-colors hover:text-gray-700"
                onClick={() => setShowAllCategories(!showAllCategories)}
              >
                {showAllCategories ? '접기' : `+${card.categoryPreferences.length - 4}개 더보기`}
              </button>
            )}
          </div>

          <div className="space-y-2">
            {card.categoryPreferences.length === 0 ? (
              <p className="py-4 text-center text-sm text-gray-500">데이터가 없습니다.</p>
            ) : (
              getTopItems(card.categoryPreferences, showAllCategories).map((category) => {
                const value = getValueByView(category, currentView);
                const isOthers = category.name === '기타';
                const totalValue = card.categoryPreferences
                  .filter((item) => item.name !== '기타')
                  .reduce((sum, item) => sum + getValueByView(item, currentView), 0);
                const percentage = !isOthers && totalValue > 0 ? Math.round((value / totalValue) * 100) : 0;

                return (
                  <div key={category.name} className="flex items-center gap-3">
                    <div className="w-12 text-right text-sm text-gray-600">
                      {category.name.includes(',') ? category.name.split(',')[0] : category.name}
                    </div>
                    <div className="relative flex-1">
                      <div className="h-6 w-full overflow-hidden rounded-full bg-gray-100">
                        {!isOthers && value > 0 && (
                          <div
                            className="flex h-full items-center justify-end rounded-full bg-gray-800 pr-2 transition-all duration-500"
                            style={{ width: `${percentage}%` }}
                          >
                            {percentage >= 10 && (
                              <span className="text-xs font-medium text-white">{percentage}%</span>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                    <div className="w-10 text-right text-xs text-gray-500">
                      {value}
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>

        {/* 취향 인사이트 */}
        <div className="rounded-lg bg-gray-50 p-4">
          <h4 className="mb-3 text-sm font-medium text-gray-700">취향 인사이트</h4>
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-xs">
              <div className="h-2 w-2 rounded-full bg-gray-800"></div>
              <span className="text-gray-600">{card.summary.topRegion}에서 가장 활발하게 활동</span>
            </div>
            <div className="flex items-center gap-2 text-xs">
              <div className="h-2 w-2 rounded-full bg-gray-800"></div>
              <span className="text-gray-600">{card.summary.topCategory} 음식을 가장 선호</span>
            </div>
            <div className="flex items-center gap-2 text-xs">
              <div className="h-2 w-2 rounded-full bg-gray-800"></div>
              <span className="text-gray-600">
                {card.regionPreferences.filter((r) => r.visits > 0).length}개 지역,
                {bucket
                  ? bucket.bucket_data_jsonb.v1_aggr_user_places_categorized_stats.filter(
                      (c) => c.visited > 0,
                    ).length
                  : card.categoryPreferences.filter((c) => c.visits > 0).length}
                개 카테고리 경험
              </span>
            </div>
          </div>
        </div>
      </div>
    </article>
  );
}
