// svelte/src/routes/feature.20250617/components/Header.svelte
<script lang="ts">
	import { Share, Search } from 'lucide-svelte';
	import Icon from '$lib/components/Icon.svelte';
</script>

<header class="sticky top-0 z-10 bg-white/80 backdrop-blur-sm border-b border-gray-100">
	<div class="max-w-3xl mx-auto px-4">
		<div class="flex items-center justify-between h-16">
			<h1 class="text-xl font-bold text-gray-900 dark:text-gray-100 flex items-center gap-2">
				유튜브
			</h1>
			<!-- <h1 class="text-2xl font-bold text-gray-900 flex items-center gap-2">
				<Icon name="youtube" class="text-red-500 w-7 h-7" />
				<span>추천 영상</span>
			</h1> -->
			<!-- <div class="flex gap-1">
				<button
					class="p-2 rounded-full text-gray-600 hover:bg-gray-100 transition-colors"
					aria-label="Search"
				>
					<Icon name="search" class="w-6 h-6" />
				</button>
			</div> -->
		</div>
	</div>
</header>

// src/widgets/Header.tsx
import { Logo } from "@/shared/ui/Logo";
import { MessageSquare, Bell } from "lucide-react";
import { Button } from "@/shared/ui";

/**
 * 상단 헤더 컴포넌트
 * 로고와 알림, 메시지 등 전역 액션 버튼을 포함합니다.
 */
export function Header() {
  return (
    <header className="fixed top-0 inset-x-0 z-50 bg-white/80 backdrop-blur-md border-b border-surface-200 dark:bg-surface-900/80 dark:border-surface-800">
      <div className="flex items-center justify-between h-14 px-4 max-w-lg mx-auto">
        <div className="flex items-center">
          <Logo />
        </div>
        <div className="flex items-center gap-2">
          {/* 메시지함 버튼 */}
          <Button variant="ghost" size="icon" className="text-surface-600 dark:text-surface-400">
            <MessageSquare className="size-5" />
          </Button>
          {/* 알림 센터 버튼 */}
          <Button variant="ghost" size="icon" className="text-surface-600 dark:text-surface-400">
            <Bell className="size-5" />
          </Button>
        </div>
      </div>
    </header>
  );
}
